CREATE TABLE combustiveis
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100)   NOT NULL,
    preco_litro NUMERIC(10, 3) NOT NULL,

    CONSTRAINT ck_combustiveis_nome_nao_vazio
        CHECK (BTRIM(nome) <> ''),
    CONSTRAINT ck_combustiveis_preco_positivo
        CHECK (preco_litro > 0)
);