CREATE TABLE
    bombas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        combustivel_id BIGINT NOT NULL,
        CONSTRAINT ck_bombas_nome_nao_vazio CHECK (BTRIM (nome) <> ''),
        CONSTRAINT fk_bombas_combustiveis FOREIGN KEY (combustivel_id) REFERENCES combustiveis (id) ON DELETE RESTRICT
    );

CREATE INDEX idx_bombas_combustivel_id ON bombas (combustivel_id);