CREATE TABLE
    abastecimentos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bomba_id BIGINT NOT NULL,
        data_abastecimento TIMESTAMPTZ NOT NULL,
        litros NUMERIC(10, 3) NOT NULL,
        preco_litro_aplicado NUMERIC(10, 3) NOT NULL,
        valor_total NUMERIC(16, 2) NOT NULL,
        CONSTRAINT fk_abastecimentos_bombas FOREIGN KEY (bomba_id) REFERENCES bombas (id) ON DELETE RESTRICT,
        CONSTRAINT ck_abastecimentos_litros_positivos CHECK (litros > 0),
        CONSTRAINT ck_abastecimentos_preco_positivo CHECK (preco_litro_aplicado > 0),
        CONSTRAINT ck_abastecimentos_total_positivo CHECK (valor_total > 0)
    );

CREATE INDEX idx_abastecimentos_bomba_id ON abastecimentos (bomba_id);