spring.datasource.url=${TEST_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/posto_gasolina_test}
spring.datasource.username=${TEST_SPRING_DATASOURCE_USERNAME:merito_test}
spring.datasource.password=${TEST_SPRING_DATASOURCE_PASSWORD:merito_test_local}

spring.jpa.hibernate.ddl-auto=validate
